### PR TITLE
Scala 2.12.2 and style

### PR DESCRIPTION
**Pull request by zifeo**

### CODE REVIEW

**Comment by zifeo** [comment]
Style is now enforced by travis according to scalafmt. New PR should run `sbt scalafmt` before being opened.

**Comment by mukel** [comment]
You have to reformat the whole repo.

**Comment by zifeo** [comment]
BuildInfo is something generated by the compilation :/. I will try a clean before, but my repo is corrupted...

**Comment by mukel** [comment]
Can you blacklist it?

**Pull request merged**
