### PR TITLE
This is the website.

### PR DESCRIPTION
**Pull request by johnstephan**

### CODE REVIEW

**Comment by zifeo** [comment]
Unzipped is better :)

**Comment by mukel** [comment]
I'd put it just on the root e.g. under a folder 'website', putting it in the resources will include all files on the bot's .jar

**Comment by zifeo** [comment]
The website should be in the resource otherwise the server cannot serve it. I think bundling both together make sens, WDYT?

**Comment by mukel** [comment]
I was thinking on using GitHub pages with a custom domain. It's a microsite, embedding it on the bot should be fine. LGTM

**Pull request closed without merging**
